import sqlite3

class SQLite:
    """ Basic wrapper class for SQLite interaction (WIP) """

    def __init__(self, dbname: str) -> None:
        """ Constructor """
        self.dbname = dbname
        self.db = sqlite3.connect(self.dbname)
        self.cursor = self.db.cursor()

    def close(self) -> None:
        """ Closes the db connection """
        self.cursor.close()
        self.db.close()

    def execute(self, statement: str, conds: tuple) -> int:
        """ Executes a SQL statement - useful for UPDATE and DELETE etc """
        self.cursor.execute(statement, conds)
        self.db.commit()
        row_count = self.cursor.rowcount
        return row_count

    def select(self, statement: str, conds: tuple) -> list:
        """ Execute a select statement and returns a list """
        results = self.cursor.execute(statement, conds).fetchall()
        return results

    def tables_exist(self, tablenames: list) -> bool:
        """ Check if tables in the supplied list exist """
        table_results = self.cursor.execute('''
            SELECT name
            FROM sqlite_master
            WHERE name IN (%s)
        ''' % ','.join('?'*len(tablenames)), tablenames).fetchall()

        if (len(table_results) == len(tablenames)):
            return True
        else:
            return False

    def insert(self, statement: str, value: tuple) -> int:
        """ Execute an insert statement and return the autogenerated row id """
        self.cursor.execute(statement, value)
        self.db.commit()
        last_row_id = self.cursor.lastrowid
        return last_row_id

    def insert_many(self, statement: str, values: tuple) -> int:
        """ Execute multiple insert statements and return the number of rows inserted """
        self.cursor.executemany(statement, values)
        self.db.commit()
        insert_row_count = self.cursor.rowcount
